### ISSUE TITLE
Staging branch intermittently crashes -- throws Error 404 (3-4 times every hour)

### ISSUE THREAD

**Issue by karlsaito** [SaitoTech/saito-lite-rust#194] opened 2022-02-09 02:45 UTC
Intermittent Error

Test Step:
1. Open https://rustest.saito.io/arcade/
2. Throws Error 404

**Error**
![image](https://user-images.githubusercontent.com/96273856/153112291-2e57bd3a-1da8-4924-b409-6107fac86ac5.png)

**Comment by trevelyan** [comment] 2022-02-09 03:53
Closing this bug report as I believe the issue is fixed and that the current deploy does not have this issue -- managed a longer 1 hour game yesterday evening with Tucho and I think we would have noticed if the server went down like this.

Suspect the likely problem here was the server crashing from a non-stop relaying of off-chain messages that would trigger database queries, eventually exhausting memory? That was an issue with a previous build that was fixed yesterday.

**Closed by trevelyan** 2022-02-09 03:53 UTC
Labels: bug, Critical, Sprint 2
