### ISSUE TITLE
Red Square: Spammable likes and comment button

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#950] opened 2022-08-18 02:06 UTC
Like and comment button can be spam clicked by one person 

![rw](https://user-images.githubusercontent.com/107991527/185276250-fe9ba7bf-30b8-4ae8-82cd-f5a1cb32da03.png)

**Comment by karlsaito** [comment] 2022-08-18 04:05
rejecting this since this is a duplicate of #935

**Closed** 2022-08-18 04:06 UTC
Labels: bug, Minor, Production, Non-game Module, Red Square
