### ISSUE TITLE
Wordblocks: First word placement goes through even without crossing a star

### ISSUE THREAD

**Issue by afkafk088** [SaitoTech/saito-lite-rust#845] opened 2022-08-04 04:13 UTC
**Issue:** 
• You should **NOT** be able to put the first word on the board without crossing a star

**Steps:**
• As the player 1, place a 3-letter word inside the boxes as shown on Fig.2

Fig.1 (This is how it's supposed to be when entering first word that's not crossing stars)
![wb1](https://user-images.githubusercontent.com/107991527/182760381-9cb57422-2770-48be-896b-f3fe9b12f5cf.png)

Fig.2 (You can place a 3 letter word within the red boxes even if they are not crossing stars)
![wb2](https://user-images.githubusercontent.com/107991527/182760405-79988485-ec0c-4e6b-a690-709058ec0a42.png)

**Comment by f8daniel** [comment] 2022-08-04 06:28
Beautiful

**Comment by estapeluo** [comment] 2022-08-04 06:45
"its not a bug, its a feature"

jokes aside, happens on staging

**Comment by estapeluo** [comment] 2022-08-04 08:22
Closing 69448fba50ec0d376e86eb96493609ce25a67d8b

**Closed by estapeluo** 2022-08-04 08:22 UTC
Labels: bug, Minor, Production, Staging
